### ISSUE TITLE
accumulate not indenting the same as [i]collect

### ISSUE THREAD

**Issue by jaawerth** [jaawerth/fennel.vim#2]
It appears that `accumulate` is still not indenting correctly, so likely needs some additional support added.

## Current indentation from plugin

```fennel
(acumulate [sum 0 _ v (ipairs [1 2 3 4 5])]
           (+ v sum))
```

## Desired indentation

```fennel
(acumulate [sum 0 _ v (ipairs [1 2 3 4 5])]
  (+ v sum))
```

**Comment by rktjmp** [comment]
```diff
- acumulate
+ accumulate
```
? I can't reproduce it.

**Comment by jaawerth** [comment]
Thanks - it's working on my end now as well so I must have missed something when I logged this.
