### ISSUE TITLE
`with-*` and `def*` indentation

### ISSUE THREAD

**Issue by rktjmp** [jaawerth/fennel.vim#6]
Per the new macros.md indentation section in 1.3.0:

> This raises the question of how to tell whether a given macro takes a
> body or not. For the forms which are part of Fennel, you can use the
> `(fennel.syntax)` function in Fennel's API: it will give you a table
> of form names, some of which have `:body? true`. For things that don't
> come with Fennel, picking a name that starts with `with-` or `def`
> will make it clearer to 3rd-party tools like text editors and `fnlfmt`
> that it's a macro which takes a body.

Setting `lispwords+=def*,with-*` is enough I think.

**Comment by rktjmp** [comment]
Actually its not enough, lispwords isnt glob-able.

**Comment by jaawerth** [comment]
Hi! Sorry for slow response; I have a local branch on another machine where I'd added `with-*` support; I'll throw in `def` and push changes tonight!
